# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "box"
  config.vm.network :private_network, ip: '10.10.10.101'

  # vagrant-specs will fail otherwise
  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end

  # we don't need synced_folder, also they might lead to failures due
  # to guest additions mismatches
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.dns.tld      = 'com'
  config.dns.patterns = /^.*public.testbox.com$/
  #---VagrantDNS::Config.check_public_suffix---#

  VagrantDNS::Config.listen = [[:udp, "127.0.0.1", 5333]]
end
