# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  # config.vm.box     = 'hashicorp/bionic64'
  config.vm.box     = "bento/ubuntu-22.10"
  # config.vm.box_url = 'http://files.vagrantup.com/precise32.box'

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.hostname = "machine"
  # config.vm.network :private_network, ip: "33.33.33.60"
  config.vm.network :private_network, type: :dhcp
  # config.vm.network :public_network, ip: "192.168.178.222", bridge: "en0: Wi-Fi (AirPort)"
  # config.vm.network :public_network, use_dhcp_assigned_default_route: true, bridge: "en0: Wi-Fi (AirPort)"

  config.dns.tld      = "test"
  config.dns.patterns = /^.*machine.test$/
  # config.dns.ip = -> (vm, opts) do
  #   ip = nil
  #   vm.communicate.execute("hostname -I | cut -d ' ' -f 1") do |type, data|
  #     ip = data.strip if type == :stdout
  #   end
  #   ip
  # end

  VagrantDNS::Config.listen = [[:udp, "127.0.0.1", 5300]]
  VagrantDNS::Config.ttl = 30

  VagrantDNS::Config.passthrough = false # :unknown
  VagrantDNS::Config.passthrough_resolver = [ [:udp, "1.0.0.1", 53], ["tcp", "1.0.0.1", 53] ]

  (1..3).each do |i|
    config.vm.define "worker#{i}" do |subconfig|
      subconfig.dns.tld = "test"
      subconfig.vm.hostname = "vagrant#{i}"
      subconfig.dns.patterns = "worker#{i}.mysite.test"
      subconfig.vm.box = "bento/ubuntu-22.10"
      config.vm.network :private_network, type: :dhcp
      # subconfig.vm.network "private_network", ip: "10.240.0.#{i+15}"
    end
  end
end
