# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box     = 'precise32'
  config.vm.box_url = 'http://files.vagrantup.com/precise32.box'

  config.dns.tld      = "test"
  config.dns.patterns = /^.*machine.test$/

  config.vm.hostname = "machine"
  # config.vm.network :private_network, ip: "33.33.33.60"
  config.vm.network :private_network, type: :dhcp
  # config.vm.network :public_network, ip: "192.168.178.222", bridge: "en0: Wi-Fi (AirPort)"
  # config.vm.network :public_network, use_dhcp_assigned_default_route: true, bridge: "en0: Wi-Fi (AirPort)"


  config.vm.synced_folder ".", "/vagrant", disabled: true

  VagrantDNS::Config.listen = [[:udp, "0.0.0.0", 5300]]
  VagrantDNS::Config.ttl = 30
end
